---
sudo: requred

language: python
python: "2.7"

env:
- distribution: centos
  version: 7
- distribution: fedora
  version: 26

services:
- docker

before_install:
- 'sudo docker pull ${distribution}:${version}'
- 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

install:
- pip install ansible
- pip install ansible-lint


script:
  # Basic role syntax check
  #- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook  ansible-playbook tests/test.yml -i tests/inventory '

notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
